project:
  title: "IC/CP-W05 BigQuery SQL Lecture 2"
  output-dir: docs
  resources:
    - ".nojekyll"

format:
  html:
    theme: 
      - cosmo       # The base theme
      - theme.scss # Your custom GoogleSQL overrides
    toc: true
    embed-resources: false